# Anderson and Hsiao estimator

Anderson and Hsiao (1981) suggested looking at the first difference estimator:

$$ y_{i,t} - y_{i,t-1} = (X_{i,t} - X_{i,t})' \beta + \gamma (y_{i,t-1} - y_{i,t-2}) + (\epsilon_{i,t} - \epsilon{i,t-1}) $$

or

$$ \Delta y_{i,t}= \Delta X_{i,t} \beta + \gamma \Delta y_{i,t-1} + \Delta \epsilon_{i,t} $$

This does not solve the endogeneity problem, since $\Delta y_{i,t-1}$ is still correlated with the error term.  AH's idea is to instrument $\Delta y_{i,t-1}$ with the past level $y_{i,t-2}$, or past difference $y_{i,t-2}-y_{i,t-3}$.  This estimator is consistent, since neither of these instruments is correlated with $\Delta \epsilon_{i,t}$, assuming error is not auto-correlated.


# Arellano-Bond estimator

Arellano and Bond (1991) expanded the idea by using additional lags of the dependent variable as instruments.  For example, both $y_{i,t-2}$ and $y_{i,t-3}$ can be used as instruments.  In fact, as $t$ increases, the number of instruments avialable also increases.  In period 3 only $y_{i,1}$ is available.  In period 4 $y_{i,1}$ and $y_{i,2}$ are available.  In period 5  $y_{i,1}$ and $y_{i,2}$ and  $y_{i,3}$ are availabe, and so on.  In other words, we'll have an instrument matrix with one row for each time period that we are instrumenting:


$$Z_i =
\begin{bmatrix}
0 & \ 0 & \ 0 & \ 0 & \  0 & \ 0 & \ \cdots & \ 0 & \  0 & \ 0 \\ y_{i,1} & \  0 & \ 0 & \ 0
& \  0 & \ 0 & \ \cdots & \ 0 & \  0 & \ 0 \\  0 & \  y_{i,1} & \ y_{i,2} &
\ 0 & \  0 & \ 0 & \ \cdots & \ 0 & \  0 & \ 0 \\  0 & \ 0 & \  0 & \
y_{i,1} & \ y_{i,2} & \ y_{i,3}  & \ \cdots & \ 0 & \  0 & \ 0  \\   \vdots  & \  \vdots & \  \vdots & \  \vdots & \  \vdots & \  \ddots  & \ \cdots & \ \vdots & \  \vdots & \ \vdots \\ 0 & \  0 & \  0 & \ 0 & \ 0 & \ \cdots  & \ 0 & \ y_{i,1} & \  \cdots & \ y_{i,T-2}
\end{bmatrix}
$$


This is the so called difference GMM estimator.

# Blundell and Bond estimator

AB model has a problem:  when the instruments are weak, the estimator is not good.  That will happen when $y$ follows random walk or near random walk.  In that case the past levels won't be a good predictor of the future changes.

BB model comes in to instrument levels with differences. In stead of differencing to remove the fixed effects, it keeps the fixed effects and difference the instruments to make them exogenous to the fixed effects.  The basic idea is that $\Delta y_{i,t}$ is not correlated with $C_i$.  Therefore it can be used as instruments in the fixed effects model without demeaning the variables.

This is implemented by so called system GMM.  In this case, we have fixed effects in the model, but do not attempt to purge the fixed effect by demeaning or first differencing.  Instead, we use past differences of $y$ as instruments, assuming $\Delta y_{i,t}$ is not correlated with $C_i$.  In this case, time-invariant variables can be used in the model.
